-- AlterEnum
ALTER TYPE "ShadowRankType" ADD VALUE IF NOT EXISTS 'KNIGHT';
ALTER TYPE "ShadowRankType" ADD VALUE IF NOT EXISTS 'BISHOP';
ALTER TYPE "ShadowRankType" ADD VALUE IF NOT EXISTS 'ROOK';
ALTER TYPE "ShadowRankType" ADD VALUE IF NOT EXISTS 'QUEEN';
ALTER TYPE "ShadowRankType" ADD VALUE IF NOT EXISTS 'KING';
